services:
  postgresql:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    networks:
      - nestjs

networks:
  nestjs:
