services:
  postgresql:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
